// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import "boxicons/css/boxicons.min.css"; // Import Boxicons CSS
// import { DoctorProvider } from "../contexts/DoctorContext"; // Import the Doctor Context Provider

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
//         <link
//           href="https://cdn.jsdelivr.net/npm/boxicons@2.1.4/css/boxicons.min.css"
//           rel="stylesheet"
//         />
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <DoctorProvider>
//           {children}
//         </DoctorProvider>
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
"use client";
import { SessionProvider } from "next-auth/react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
